In [16]:
from langchain.utilities import SQLDatabase
from langchain.llms import OpenAI
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.agents.agent_types import AgentType

# loads the .env file
from dotenv import load_dotenv
load_dotenv()

import langchain
langchain.debug = True

In [17]:
db = SQLDatabase.from_uri("sqlite:///chinook.db")

# check that the database has been instantiated correctly
db.get_usable_table_names()

['albums',
 'artists',
 'customers',
 'employees',
 'genres',
 'invoice_items',
 'invoices',
 'media_types',
 'playlist_track',
 'playlists',
 'tracks']

In [18]:
llm = OpenAI(temperature=0, verbose=True)

In [19]:
agent_executor = create_sql_agent(
    llm=llm,
    toolkit=SQLDatabaseToolkit(db=db, llm=llm),
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
)

In [23]:
agent_executor.run(
    "How many employees are there?"
)

[chain/start] [1:chain:AgentExecutor] Entering Chain run with input:
{
  "input": "How many employees are there?"
}
[chain/start] [1:chain:AgentExecutor > 2:chain:LLMChain] Entering Chain run with input:
{
  "input": "How many employees are there?",
  "agent_scratchpad": "",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: How many employees are there?\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables."
  ]
}
[llm/end] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:OpenAI] [1.44s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "Action: sql_db_list_tables\nAction Input: ",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 641,
      "completion_tokens": 15,
      "prompt_tokens": 626
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 2:chain:LLMChain] [1.44s] Exiting Chain run with output:
{
  "text": "Action: sql_db_list_tables\nAction Input: "
}
[tool/start] [1:chain:AgentExecutor > 4:tool:sql_db_list_tables] Entering Tool run with input:
""
[tool/end] [1:chain:AgentExecutor > 4:tool:sql_db_list_tables] [0ms] Exiting Tool run with output:
"albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks"
[chain/start] [1:chain:AgentExecutor > 5:chain:LLMChain] Entering Chain run with input:
{
  "input": "How many employees are there?",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 5:chain:LLMChain > 6:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: How many employees are there?\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.\nAction: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought:"
  ]
}
[llm/end] [1:chain:AgentExecutor > 5:chain:LLMChain > 6:llm:OpenAI] [2.30s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": " The table I need is employees.\nAction: sql_db_schema\nAction Input: employees",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 700,
      "completion_tokens": 21,
      "prompt_tokens": 679
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 5:chain:LLMChain] [2.30s] Exiting Chain run with output:
{
  "text": " The table I need is employees.\nAction: sql_db_schema\nAction Input: employees"
}
[tool/start] [1:chain:AgentExecutor > 7:tool:sql_db_schema] Entering Tool run with input:
"employees"
[tool/end] [1:chain:AgentExecutor > 7:tool:sql_db_schema] [9ms] Exiting Tool run with output:
"CREATE TABLE employees (
	"EmployeeId" INTEGER NOT NULL,
	"LastName" NVARCHAR(20) NOT NULL,
	"FirstName" NVARCHAR(20) NOT NULL,
	"Title" NVARCHAR(30),
	"ReportsTo" INTEGER,
	"BirthDate" DATETIME,
	"HireDate" DATETIME,
	"Address" NVARCHAR(70),
	"City" NVARCHAR(40),
	"State" NVARCHAR(40),
	"Country" NVARCHAR(40),
	"PostalCode" NVARCHAR(10),
	"Phone" NVARCHAR(24),
	"Fax" NVARCHAR(24),
	"Email" NVARCHAR(60),
	PRIMARY KEY ("EmployeeId"),
	FOREIGN KEY("ReportsTo") REFERENCES employees ("EmployeeId")
)

/*
3 rows from employees table:
EmployeeId	LastName	FirstName	Title	ReportsTo	BirthDate	HireDate	Address	City	State	Country	PostalCode	Phone	Fax	Email
1	Adams	Andrew	General Manager	None	1962-02-18 00:00:00	2002-08-14 00:00:00	11120 Jasper Ave NW	Edmonton	AB	Canada	T5K 2N1	+1 (780) 428-9482	+1 (780) 428-3457	andrew@chinookcorp.com
2	Edwards	Nancy	Sales Manager	1	1958-12-08 00:00:00	2002-05-01 00:00:00	825 8 Ave SW	Calgary	AB	Canada	T2P 2T3	+1 (403) 262-3443	+1 (403) 262-3322	nancy@chinookcorp.com
3	Peacock	Jane	Sales Support Agent	2	1973-08-29 00:00:00	2002-04-01 00:00:00	1111 6 Ave SW	Calgary	AB	Canada	T2P 5M5	+1 (403) 262-3443	+1 (403) 262-6712	jane@chinookcorp.com
*/"
[chain/start] [1:chain:AgentExecutor > 8:chain:LLMChain] Entering Chain run with input:
{
  "input": "How many employees are there?",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: The table I need is employees.\nAction: sql_db_schema\nAction Input: employees\nObservation: \nCREATE TABLE employees (\n\t\"EmployeeId\" INTEGER NOT NULL, \n\t\"LastName\" NVARCHAR(20) NOT NULL, \n\t\"FirstName\" NVARCHAR(20) NOT NULL, \n\t\"Title\" NVARCHAR(30), \n\t\"ReportsTo\" INTEGER, \n\t\"BirthDate\" DATETIME, \n\t\"HireDate\" DATETIME, \n\t\"Address\" NVARCHAR(70), \n\t\"City\" NVARCHAR(40), \n\t\"State\" NVARCHAR(40), \n\t\"Country\" NVARCHAR(40), \n\t\"PostalCode\" NVARCHAR(10), \n\t\"Phone\" NVARCHAR(24), \n\t\"Fax\" NVARCHAR(24), \n\t\"Email\" NVARCHAR(60), \n\tPRIMARY KEY (\"EmployeeId\"), \n\tFOREIGN KEY(\"ReportsTo\") REFERENCES employees (\"EmployeeId\")\n)\n\n/*\n3 rows from employees table:\nEmployeeId\tLastName\tFirstName\tTitle\tReportsTo\tBirthDate\tHireDate\tAddress\tCity\tState\tCountry\tPostalCode\tPhone\tFax\tEmail\n1\tAdams\tAndrew\tGeneral Manager\tNone\t1962-02-18 00:00:00\t2002-08-14 00:00:00\t11120 Jasper Ave NW\tEdmonton\tAB\tCanada\tT5K 2N1\t+1 (780) 428-9482\t+1 (780) 428-3457\tandrew@chinookcorp.com\n2\tEdwards\tNancy\tSales Manager\t1\t1958-12-08 00:00:00\t2002-05-01 00:00:00\t825 8 Ave SW\tCalgary\tAB\tCanada\tT2P 2T3\t+1 (403) 262-3443\t+1 (403) 262-3322\tnancy@chinookcorp.com\n3\tPeacock\tJane\tSales Support Agent\t2\t1973-08-29 00:00:00\t2002-04-01 00:00:00\t1111 6 Ave SW\tCalgary\tAB\tCanada\tT2P 5M5\t+1 (403) 262-3443\t+1 (403) 262-6712\tjane@chinookcorp.com\n*/\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 8:chain:LLMChain > 9:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: How many employees are there?\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.\nAction: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: The table I need is employees.\nAction: sql_db_schema\nAction Input: employees\nObservation: \nCREATE TABLE employees (\n\t\"EmployeeId\" INTEGER NOT NULL, \n\t\"LastName\" NVARCHAR(20) NOT NULL, \n\t\"FirstName\" NVARCHAR(20) NOT NULL, \n\t\"Title\" NVARCHAR(30), \n\t\"ReportsTo\" INTEGER, \n\t\"BirthDate\" DATETIME, \n\t\"HireDate\" DATETIME, \n\t\"Address\" NVARCHAR(70), \n\t\"City\" NVARCHAR(40), \n\t\"State\" NVARCHAR(40), \n\t\"Country\" NVARCHAR(40), \n\t\"PostalCode\" NVARCHAR(10), \n\t\"Phone\" NVARCHAR(24), \n\t\"Fax\" NVARCHAR(24), \n\t\"Email\" NVARCHAR(60), \n\tPRIMARY KEY (\"EmployeeId\"), \n\tFOREIGN KEY(\"ReportsTo\") REFERENCES employees (\"EmployeeId\")\n)\n\n/*\n3 rows from employees table:\nEmployeeId\tLastName\tFirstName\tTitle\tReportsTo\tBirthDate\tHireDate\tAddress\tCity\tState\tCountry\tPostalCode\tPhone\tFax\tEmail\n1\tAdams\tAndrew\tGeneral Manager\tNone\t1962-02-18 00:00:00\t2002-08-14 00:00:00\t11120 Jasper Ave NW\tEdmonton\tAB\tCanada\tT5K 2N1\t+1 (780) 428-9482\t+1 (780) 428-3457\tandrew@chinookcorp.com\n2\tEdwards\tNancy\tSales Manager\t1\t1958-12-08 00:00:00\t2002-05-01 00:00:00\t825 8 Ave SW\tCalgary\tAB\tCanada\tT2P 2T3\t+1 (403) 262-3443\t+1 (403) 262-3322\tnancy@chinookcorp.com\n3\tPeacock\tJane\tSales Support Agent\t2\t1973-08-29 00:00:00\t2002-04-01 00:00:00\t1111 6 Ave SW\tCalgary\tAB\tCanada\tT2P 5M5\t+1 (403) 262-3443\t+1 (403) 262-6712\tjane@chinookcorp.com\n*/\nThought:"
  ]
}
[llm/end] [1:chain:AgentExecutor > 8:chain:LLMChain > 9:llm:OpenAI] [1.34s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": " I should query the employees table to get the number of employees.\nAction: sql_db_query\nAction Input: SELECT COUNT(*) FROM employees",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 1278,
      "completion_tokens": 32,
      "prompt_tokens": 1246
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 8:chain:LLMChain] [1.34s] Exiting Chain run with output:
{
  "text": " I should query the employees table to get the number of employees.\nAction: sql_db_query\nAction Input: SELECT COUNT(*) FROM employees"
}
[tool/start] [1:chain:AgentExecutor > 10:tool:sql_db_query] Entering Tool run with input:
"SELECT COUNT(*) FROM employees"
[tool/end] [1:chain:AgentExecutor > 10:tool:sql_db_query] [1ms] Exiting Tool run with output:
"[(8,)]"
[chain/start] [1:chain:AgentExecutor > 11:chain:LLMChain] Entering Chain run with input:
{
  "input": "How many employees are there?",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: The table I need is employees.\nAction: sql_db_schema\nAction Input: employees\nObservation: \nCREATE TABLE employees (\n\t\"EmployeeId\" INTEGER NOT NULL, \n\t\"LastName\" NVARCHAR(20) NOT NULL, \n\t\"FirstName\" NVARCHAR(20) NOT NULL, \n\t\"Title\" NVARCHAR(30), \n\t\"ReportsTo\" INTEGER, \n\t\"BirthDate\" DATETIME, \n\t\"HireDate\" DATETIME, \n\t\"Address\" NVARCHAR(70), \n\t\"City\" NVARCHAR(40), \n\t\"State\" NVARCHAR(40), \n\t\"Country\" NVARCHAR(40), \n\t\"PostalCode\" NVARCHAR(10), \n\t\"Phone\" NVARCHAR(24), \n\t\"Fax\" NVARCHAR(24), \n\t\"Email\" NVARCHAR(60), \n\tPRIMARY KEY (\"EmployeeId\"), \n\tFOREIGN KEY(\"ReportsTo\") REFERENCES employees (\"EmployeeId\")\n)\n\n/*\n3 rows from employees table:\nEmployeeId\tLastName\tFirstName\tTitle\tReportsTo\tBirthDate\tHireDate\tAddress\tCity\tState\tCountry\tPostalCode\tPhone\tFax\tEmail\n1\tAdams\tAndrew\tGeneral Manager\tNone\t1962-02-18 00:00:00\t2002-08-14 00:00:00\t11120 Jasper Ave NW\tEdmonton\tAB\tCanada\tT5K 2N1\t+1 (780) 428-9482\t+1 (780) 428-3457\tandrew@chinookcorp.com\n2\tEdwards\tNancy\tSales Manager\t1\t1958-12-08 00:00:00\t2002-05-01 00:00:00\t825 8 Ave SW\tCalgary\tAB\tCanada\tT2P 2T3\t+1 (403) 262-3443\t+1 (403) 262-3322\tnancy@chinookcorp.com\n3\tPeacock\tJane\tSales Support Agent\t2\t1973-08-29 00:00:00\t2002-04-01 00:00:00\t1111 6 Ave SW\tCalgary\tAB\tCanada\tT2P 5M5\t+1 (403) 262-3443\t+1 (403) 262-6712\tjane@chinookcorp.com\n*/\nThought: I should query the employees table to get the number of employees.\nAction: sql_db_query\nAction Input: SELECT COUNT(*) FROM employees\nObservation: [(8,)]\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 11:chain:LLMChain > 12:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [

'There are 8 employees.'

In [24]:
# recover from an error
agent_executor.run("Who are the top 3 best selling artists?")

[chain/start] [1:chain:AgentExecutor] Entering Chain run with input:
{
  "input": "Who are the top 3 best selling artists?"
}
[chain/start] [1:chain:AgentExecutor > 2:chain:LLMChain] Entering Chain run with input:
{
  "input": "Who are the top 3 best selling artists?",
  "agent_scratchpad": "",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: Who are the top 3 best selling artists?\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables."
  ]
}
[llm/end] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:OpenAI] [1.65s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "Action: sql_db_list_tables\nAction Input: ",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 644,
      "completion_tokens": 15,
      "prompt_tokens": 629
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 2:chain:LLMChain] [1.65s] Exiting Chain run with output:
{
  "text": "Action: sql_db_list_tables\nAction Input: "
}
[tool/start] [1:chain:AgentExecutor > 4:tool:sql_db_list_tables] Entering Tool run with input:
""
[tool/end] [1:chain:AgentExecutor > 4:tool:sql_db_list_tables] [0ms] Exiting Tool run with output:
"albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks"
[chain/start] [1:chain:AgentExecutor > 5:chain:LLMChain] Entering Chain run with input:
{
  "input": "Who are the top 3 best selling artists?",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 5:chain:LLMChain > 6:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: Who are the top 3 best selling artists?\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.\nAction: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought:"
  ]
}
[llm/end] [1:chain:AgentExecutor > 5:chain:LLMChain > 6:llm:OpenAI] [1.21s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": " I should query the schema of the albums and artists tables.\nAction: sql_db_schema\nAction Input: albums, artists",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 710,
      "completion_tokens": 28,
      "prompt_tokens": 682
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 5:chain:LLMChain] [1.21s] Exiting Chain run with output:
{
  "text": " I should query the schema of the albums and artists tables.\nAction: sql_db_schema\nAction Input: albums, artists"
}
[tool/start] [1:chain:AgentExecutor > 7:tool:sql_db_schema] Entering Tool run with input:
"albums, artists"
[tool/end] [1:chain:AgentExecutor > 7:tool:sql_db_schema] [3ms] Exiting Tool run with output:
"CREATE TABLE albums (
	"AlbumId" INTEGER NOT NULL,
	"Title" NVARCHAR(160) NOT NULL,
	"ArtistId" INTEGER NOT NULL,
	PRIMARY KEY ("AlbumId"),
	FOREIGN KEY("ArtistId") REFERENCES artists ("ArtistId")
)

/*
3 rows from albums table:
AlbumId	Title	ArtistId
1	For Those About To Rock We Salute You	1
2	Balls to the Wall	2
3	Restless and Wild	2
*/


CREATE TABLE artists (
	"ArtistId" INTEGER NOT NULL,
	"Name" NVARCHAR(120),
	PRIMARY KEY ("ArtistId")
)

/*
3 rows from artists table:
ArtistId	Name
1	AC/DC
2	Accept
3	Aerosmith
*/"
[chain/start] [1:chain:AgentExecutor > 8:chain:LLMChain] Entering Chain run with input:
{
  "input": "Who are the top 3 best selling artists?",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: I should query the schema of the albums and artists tables.\nAction: sql_db_schema\nAction Input: albums, artists\nObservation: \nCREATE TABLE albums (\n\t\"AlbumId\" INTEGER NOT NULL, \n\t\"Title\" NVARCHAR(160) NOT NULL, \n\t\"ArtistId\" INTEGER NOT NULL, \n\tPRIMARY KEY (\"AlbumId\"), \n\tFOREIGN KEY(\"ArtistId\") REFERENCES artists (\"ArtistId\")\n)\n\n/*\n3 rows from albums table:\nAlbumId\tTitle\tArtistId\n1\tFor Those About To Rock We Salute You\t1\n2\tBalls to the Wall\t2\n3\tRestless and Wild\t2\n*/\n\n\nCREATE TABLE artists (\n\t\"ArtistId\" INTEGER NOT NULL, \n\t\"Name\" NVARCHAR(120), \n\tPRIMARY KEY (\"ArtistId\")\n)\n\n/*\n3 rows from artists table:\nArtistId\tName\n1\tAC/DC\n2\tAccept\n3\tAerosmith\n*/\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 8:chain:LLMChain > 9:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: Who are the top 3 best selling artists?\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.\nAction: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: I should query the schema of the albums and artists tables.\nAction: sql_db_schema\nAction Input: albums, artists\nObservation: \nCREATE TABLE albums (\n\t\"AlbumId\" INTEGER NOT NULL, \n\t\"Title\" NVARCHAR(160) NOT NULL, \n\t\"ArtistId\" INTEGER NOT NULL, \n\tPRIMARY KEY (\"AlbumId\"), \n\tFOREIGN KEY(\"ArtistId\") REFERENCES artists (\"ArtistId\")\n)\n\n/*\n3 rows from albums table:\nAlbumId\tTitle\tArtistId\n1\tFor Those About To Rock We Salute You\t1\n2\tBalls to the Wall\t2\n3\tRestless and Wild\t2\n*/\n\n\nCREATE TABLE artists (\n\t\"ArtistId\" INTEGER NOT NULL, \n\t\"Name\" NVARCHAR(120), \n\tPRIMARY KEY (\"ArtistId\")\n)\n\n/*\n3 rows from artists table:\nArtistId\tName\n1\tAC/DC\n2\tAccept\n3\tAerosmith\n*/\nThought:"
  ]
}
[llm/end] [1:chain:AgentExecutor > 8:chain:LLMChain > 9:llm:OpenAI] [2.26s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": " I should query the albums table to get the top 3 best selling artists.\nAction: sql_db_query\nAction Input: SELECT a.Name, COUNT(*) AS 'Number of Albums Sold' FROM albums a JOIN artists b ON a.ArtistId = b.ArtistId GROUP BY a.Name ORDER BY COUNT(*) DESC LIMIT 3;",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 1008,
      "completion_tokens": 78,
      "prompt_tokens": 930
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 8:chain:LLMChain] [2.26s] Exiting Chain run with output:
{
  "text": " I should query the albums table to get the top 3 best selling artists.\nAction: sql_db_query\nAction Input: SELECT a.Name, COUNT(*) AS 'Number of Albums Sold' FROM albums a JOIN artists b ON a.ArtistId = b.ArtistId GROUP BY a.Name ORDER BY COUNT(*) DESC LIMIT 3;"
}
[tool/start] [1:chain:AgentExecutor > 10:tool:sql_db_query] Entering Tool run with input:
"SELECT a.Name, COUNT(*) AS 'Number of Albums Sold' FROM albums a JOIN artists b ON a.ArtistId = b.ArtistId GROUP BY a.Name ORDER BY COUNT(*) DESC LIMIT 3;"
[tool/end] [1:chain:AgentExecutor > 10:tool:sql_db_query] [0ms] Exiting Tool run with output:
"Error: (sqlite3.OperationalError) no such column: a.Name
[SQL: SELECT a.Name, COUNT(*) AS 'Number of Albums Sold' FROM albums a JOIN artists b ON a.ArtistId = b.ArtistId GROUP BY a.Name ORDER BY COUNT(*) DESC LIMIT 3;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)"
[chain/start] [1:chain:AgentExecutor > 11:chain:LLMChain] Entering Chain run with input:
{
  "input": "Who are the top 3 best selling artists?",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: I should query the schema of the albums and artists tables.\nAction: sql_db_schema\nAction Input: albums, artists\nObservation: \nCREATE TABLE albums (\n\t\"AlbumId\" INTEGER NOT NULL, \n\t\"Title\" NVARCHAR(160) NOT NULL, \n\t\"ArtistId\" INTEGER NOT NULL, \n\tPRIMARY KEY (\"AlbumId\"), \n\tFOREIGN KEY(\"ArtistId\") REFERENCES artists (\"ArtistId\")\n)\n\n/*\n3 rows from albums table:\nAlbumId\tTitle\tArtistId\n1\tFor Those About To Rock We Salute You\t1\n2\tBalls to the Wall\t2\n3\tRestless and Wild\t2\n*/\n\n\nCREATE TABLE artists (\n\t\"ArtistId\" INTEGER NOT NULL, \n\t\"Name\" NVARCHAR(120), \n\tPRIMARY KEY (\"ArtistId\")\n)\n\n/*\n3 rows from artists table:\nArtistId\tName\n1\tAC/DC\n2\tAccept\n3\tAerosmith\n*/\nThought: I should query the albums table to get the top 3 best selling artists.\nAction: sql_db_query\nAction Input: SELECT a.Name, COUNT(*) AS 'Number of Albums Sold' FROM albums a JOIN artists b ON a.ArtistId = b.ArtistId GROUP BY a.Name ORDER BY COUNT(*) DESC LIMIT 3;\nObservation: Error: (sqlite3.OperationalError) no such column: a.Name\n[SQL: SELECT a.Name, COUNT(*) AS 'Number of Albums Sold' FROM albums a JOIN artists b ON a.ArtistId = b.ArtistId GROUP BY a.Name ORDER BY COUNT(*) DESC LIMIT 3;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 11:chain:LLMChain > 12:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [

'The top 3 best selling artists are Iron Maiden, Led Zeppelin, and Deep Purple.'

In [21]:
agent_executor.run("Describe the playlisttrack table")

[chain/start] [1:chain:AgentExecutor] Entering Chain run with input:
{
  "input": "Describe the playlisttrack table"
}
[chain/start] [1:chain:AgentExecutor > 2:chain:LLMChain] Entering Chain run with input:
{
  "input": "Describe the playlisttrack table",
  "agent_scratchpad": "",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: Describe the playlisttrack table\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables."
  ]
}
[llm/end] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:OpenAI] [1.76s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "Action: sql_db_list_tables\nAction Input: ",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 641,
      "completion_tokens": 15,
      "prompt_tokens": 626
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 2:chain:LLMChain] [1.76s] Exiting Chain run with output:
{
  "text": "Action: sql_db_list_tables\nAction Input: "
}
[tool/start] [1:chain:AgentExecutor > 4:tool:sql_db_list_tables] Entering Tool run with input:
""
[tool/end] [1:chain:AgentExecutor > 4:tool:sql_db_list_tables] [0ms] Exiting Tool run with output:
"albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks"
[chain/start] [1:chain:AgentExecutor > 5:chain:LLMChain] Entering Chain run with input:
{
  "input": "Describe the playlisttrack table",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 5:chain:LLMChain > 6:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: Describe the playlisttrack table\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.\nAction: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought:"
  ]
}
[llm/end] [1:chain:AgentExecutor > 5:chain:LLMChain > 6:llm:OpenAI] [1.49s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": " The playlisttrack table looks relevant, so I should query the schema of that table.\nAction: sql_db_schema\nAction Input: playlist_track",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 712,
      "completion_tokens": 33,
      "prompt_tokens": 679
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 5:chain:LLMChain] [1.49s] Exiting Chain run with output:
{
  "text": " The playlisttrack table looks relevant, so I should query the schema of that table.\nAction: sql_db_schema\nAction Input: playlist_track"
}
[tool/start] [1:chain:AgentExecutor > 7:tool:sql_db_schema] Entering Tool run with input:
"playlist_track"
[tool/end] [1:chain:AgentExecutor > 7:tool:sql_db_schema] [5ms] Exiting Tool run with output:
"CREATE TABLE playlist_track (
	"PlaylistId" INTEGER NOT NULL,
	"TrackId" INTEGER NOT NULL,
	PRIMARY KEY ("PlaylistId", "TrackId"),
	FOREIGN KEY("PlaylistId") REFERENCES playlists ("PlaylistId"),
	FOREIGN KEY("TrackId") REFERENCES tracks ("TrackId")
)

/*
3 rows from playlist_track table:
PlaylistId	TrackId
1	3402
1	3389
1	3390
*/"
[chain/start] [1:chain:AgentExecutor > 8:chain:LLMChain] Entering Chain run with input:
{
  "input": "Describe the playlisttrack table",
  "agent_scratchpad": "Action: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: The playlisttrack table looks relevant, so I should query the schema of that table.\nAction: sql_db_schema\nAction Input: playlist_track\nObservation: \nCREATE TABLE playlist_track (\n\t\"PlaylistId\" INTEGER NOT NULL, \n\t\"TrackId\" INTEGER NOT NULL, \n\tPRIMARY KEY (\"PlaylistId\", \"TrackId\"), \n\tFOREIGN KEY(\"PlaylistId\") REFERENCES playlists (\"PlaylistId\"), \n\tFOREIGN KEY(\"TrackId\") REFERENCES tracks (\"TrackId\")\n)\n\n/*\n3 rows from playlist_track table:\nPlaylistId\tTrackId\n1\t3402\n1\t3389\n1\t3390\n*/\nThought:",
  "stop": [
    "\nObservation:",
    "\n\tObservation:"
  ]
}
[llm/start] [1:chain:AgentExecutor > 8:chain:LLMChain > 9:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "You are an agent designed to interact with a SQL database.\nGiven an input question, create a syntactically correct sqlite query to run, then look at the results of the query and return the answer.\nUnless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 10 results.\nYou can order the results by a relevant column to return the most interesting examples in the database.\nNever query for all the columns from a specific table, only ask for the relevant columns given the question.\nYou have access to tools for interacting with the database.\nOnly use the below tools. Only use the information returned by the below tools to construct your final answer.\nYou MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.\n\nDO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.\n\nIf the question does not seem related to the database, just return \"I don't know\" as the answer.\n\n\nsql_db_query: Input to this tool is a detailed and correct SQL query, output is a result from the database. If the query is not correct, an error message will be returned. If an error is returned, rewrite the query, check the query, and try again. If you encounter an issue with Unknown column 'xxxx' in 'field list', using sql_db_schema to query the correct table fields.\nsql_db_schema: Input to this tool is a comma-separated list of tables, output is the schema and sample rows for those tables. Be sure that the tables actually exist by calling sql_db_list_tables first! Example Input: 'table1, table2, table3'\nsql_db_list_tables: Input is an empty string, output is a comma separated list of tables in the database.\nsql_db_query_checker: Use this tool to double check if your query is correct before executing it. Always use this tool before executing a query with sql_db_query!\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: Describe the playlisttrack table\nThought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.\nAction: sql_db_list_tables\nAction Input: \nObservation: albums, artists, customers, employees, genres, invoice_items, invoices, media_types, playlist_track, playlists, tracks\nThought: The playlisttrack table looks relevant, so I should query the schema of that table.\nAction: sql_db_schema\nAction Input: playlist_track\nObservation: \nCREATE TABLE playlist_track (\n\t\"PlaylistId\" INTEGER NOT NULL, \n\t\"TrackId\" INTEGER NOT NULL, \n\tPRIMARY KEY (\"PlaylistId\", \"TrackId\"), \n\tFOREIGN KEY(\"PlaylistId\") REFERENCES playlists (\"PlaylistId\"), \n\tFOREIGN KEY(\"TrackId\") REFERENCES tracks (\"TrackId\")\n)\n\n/*\n3 rows from playlist_track table:\nPlaylistId\tTrackId\n1\t3402\n1\t3389\n1\t3390\n*/\nThought:"
  ]
}
[llm/end] [1:chain:AgentExecutor > 8:chain:LLMChain > 9:llm:OpenAI] [1.97s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": " I now know the final answer\nFinal Answer: The playlist_track table contains two columns, PlaylistId and TrackId, which are both integers and form a primary key. It also has two foreign keys, one to the playlists table and one to the tracks table.",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "total_tokens": 906,
      "completion_tokens": 56,
      "prompt_tokens": 850
    },
    "model_name": "text-davinci-003"
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 8:chain:LLMChain] [1.98s] Exiting Chain run with output:
{
  "text": " I now know the final answer\nFinal Answer: The playlist_track table contains two columns, PlaylistId and TrackId, which are both integers and form a primary key. It also has two foreign keys, one to the playlists table and one to the tracks table."
}
[chain/end] [1:chain:AgentExecutor] [5.24s] Exiting Chain run with output:
{
  "output": "The playlist_track table contains two columns, PlaylistId and TrackId, which are both integers and form a primary key. It also has two foreign keys, one to the playlists table and one to the tracks table."
}

'The playlist_track table contains two columns, PlaylistId and TrackId, which are both integers and form a primary key. It also has two foreign keys, one to the playlists table and one to the tracks table.'